Rename command implemented

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -613,12 +613,14 @@ cmd_unmount() {
     return 0
   fi
   zfs umount ${be}
+  local mountroot=$(zfs get -H -o value mountpoint ${be})
   zfs list -H -o name,beadm:mountpoint -r ${be} \
     | while read NAME MOUNTPOINT;do
       if ! prop_is_inherited mountpoint ${NAME};then
         zfs set mountpoint=${MOUNTPOINT} ${NAME}
       fi
     done
+  rm -fr ${mountroot}
   return 0
 }
 cmd_umount(){
@@ -661,8 +663,20 @@ cmd_activate() {
 }
 
 cmd_rename() {
-  echo "Not Implemented"
-  return 1
+  if [ ${#} -ne 2 ];then
+    usage
+    return $?
+  fi
+  local old_bename=${1}
+  local new_bename=${2}
+  if ! be_exists $(get_bebase)/$old_bename; then
+    echo "ERROR: Boot environment '$1' does not exist"
+    return 1
+  fi
+  if ! zfs rename $(get_bebase)/$old_bename $(get_bebase)/$new_bename; then
+    return $?
+  fi
+  return 0
 }
 
 SUBCMD=$(get_command $1)
