Command mount and unmount implemented

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -145,6 +145,15 @@ be_exists() {
   return $?
 }
 
+# be_is_mounted: dataset -> 0|1
+be_is_mounted() {
+  local dataset=${1}
+  if [ "$(zfs get -H -o value mounted ${dataset})" = "yes" ];then
+    return 0
+  fi
+  return 1
+}
+
 # be_isclone: fulldatasetname -> 0|1
 be_isclone() { # 1=DATASET
   if zfs list ${1} 1> /dev/null 2> /dev/null;then
@@ -567,19 +576,29 @@ cmd_mount() {
   local bename=${1}
   local be=$(get_bebase)/${bename}
   if ! be_exists $be; then
-    echo "ERROR: Boot environment '$1' does not exist"
+    echo "ERROR: Boot environment '$bename' does not exist" >&2
+    return 1
+  fi
+  if be_is_mounted $be; then
+    echo "ERROR: Boot environment '$bename' already mounted" >&2
     return 1
   fi
   zfs list -H -o name,mountpoint -r ${be} \
     | while read NAME MOUNTPOINT;do
+      [[ ${MOUNTPOINT} =~ ^/beadm/${bename} ]] && continue
       zfs set beadm:mountpoint=${MOUNTPOINT} ${NAME}
       zfs set canmount=noauto ${NAME}
-      if ! prop_is_inherited mountpoint ${NAME};then
+      if [ "${NAME}" = "${be}" ];then
+        zfs set mountpoint=/beadm/${bename} ${NAME}
+      elif ! prop_is_inherited mountpoint ${NAME};then
         zfs set mountpoint=/beadm/${bename}${MOUNTPOINT} ${NAME}
       fi
     done
-  echo "Not Implemented"
-  return 1
+  zfs list -H -o name -s name -r ${be} \
+    | while read NAME;do
+      zfs mount ${NAME}
+    done
+  return 0
 }
 
 cmd_unmount() {
@@ -589,14 +608,18 @@ cmd_unmount() {
     echo "ERROR: Boot environment '$1' does not exist"
     return 1
   fi
-  zfs get beadm:mountpoint -H -o "name,value,source" -r ${be} \
+  if ! be_is_mounted $be; then
+    echo "Boot environment '$bename' not mounted"
+    return 0
+  fi
+  zfs umount ${be}
+  zfs list -H -o name,beadm:mountpoint -r ${be} \
     | while read NAME MOUNTPOINT;do
       if ! prop_is_inherited mountpoint ${NAME};then
         zfs set mountpoint=${MOUNTPOINT} ${NAME}
       fi
     done
-  echo "Not Implemented"
-  return 1
+  return 0
 }
 cmd_umount(){
   cmd_unmount $@
